theme: jekyll-theme-cayman
title: French
description: Fun ways to improve your French!
github:
 page2: home.html
 page3: grammar.html 
 page4: vocaublary.html
 page5: sports.html
 page6: social-media.html
 page7: holidays.html
 page8: environment.html
 page9: translation.html
